application_name: "myapp"
database_name: "db"
path: "/opt/{{ application_name }}/"
python_version: "3.7"
backend_git_repo: "https://{{ gituser | urlencode }}:{{ gitpassword | urlencode }}@https://github.com/BinaryOverdrive42/some_project/tree/master/backend.git"
temp_backend_path: "/temp/{{ application_name }}/backend/"
backend_path: "/opt/{{ application_name }}/backend/"
frontend_git_repo: "https://{{ gituser | urlencode }}:{{ gitpassword | urlencode }}@https://github.com/BinaryOverdrive42/some_project/tree/master/frontend.git"
temp_frontend_path: "~/builds/{{ application_name }}/frontend/"
frontend_path: "/opt/{{ application_name }}/frontend/"